name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-php@v2
        with:
          php-version: '8.2'
      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist --ignore-platform-reqs
      - name: Run phpstan
        run: vendor/bin/phpstan analyse -c phpstan.neon.dist
      - name: Run phpunit
        run: vendor/bin/phpunit -c phpunit.xml.dist
